---
- name: BIG-IP Upload and Install Update
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
    - name: Setup provider
      set_fact:
        provider:
          server: "{{private_ip}}"
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
          server_port: 443
          validate_certs: false
          no_f5_teem: false
        trusted_checksum: "{{lookup('file', '{{repo_path}}/{{f5_image}}.md5').split(' ').0}}"


    - name: Print trusted checksum
      debug:
        msg: '{{trusted_checksum}}'

    - name: Upload image to device
      bigip_software_image:
        image: '{{repo_path}}/{{f5_image}}'
        provider: "{{provider}}"
      delegate_to: localhost
      register: checksum

    #- name: Verify Checksum
    #  failed_when: calc_checksum.stdout.split(' ').0 != lookup('file', '{{repo_path}}/{{f5_image}}.md5').split(' ').0

    - name: Get checksum
      shell: md5sum /shared/images/{{f5_image}}
      register: calc_checksum
      failed_when: calc_checksum.stdout.split(' ').0 != {{trusted_checksum}}
      
    - name: Print Checksums
      debug:
        msg: 
          - "calulated md5sum is {{checksum.stdout.split(' ').0}}"
          -  "trusted md5sum is {{lookup('file', '{{repo_path}}/{{f5_image}}.md5').split(' ').0}}"

    - name: Ensure an existing image is installed in specified volume
      bigip_software_install:
        image: '{{f5_image}}'
        volume: HD1.2
        state: installed
        provider: "{{provider}}"
      delegate_to: localhost

    - name: Activate the new image and reboot into that volume
    # For some reason this doesn't activate or reboot the system.  Issue #2374 has been opened to investigate
    # Response on #2374 is they are not going to fix it and NEXT will be great.
      bigip_software_install:
        image: '{{f5_image}}'
        volume: HD1.2
        state: activated
        provider: "{{provider}}"
      delegate_to: localhost

    